### ISSUE TITLE
Firefox doesn't keep its original window size after it's reduced to the taskbar

### ISSUE THREAD

**Issue by terrybr** [digitalcreations/MaxTo#339]
**Describe the bug**
I have 3 widescreen monitors. My main browser is Firefox 65.0 (64bits).   When I reduce fully maximized browser to the taskbar and click back on its taskbar icon to maximize it again, its size becomes a little rectangle.  It seems that it doesn't keep its previous size, and this is happening on each of my screens

**To Reproduce**
1. Launch Firefox
2. Maximize it
3. Click on reduce to taskbar
4. Click on the Firefox taskbar icon
5. The Firefox window size is a small rectangle

**Expected behavior**
The Firefox window size should not resize and should keep its size from when I reduced it to the taskbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/378788/52746618-efc5a300-2faf-11e9-8e9c-174865031cd2.png)

**System information:**
 - Windows version: 10
 - MaxTo version: 2.0.0-beta10

**Additional Info**
The screenshot is showing the size after I clicked back on Firefox which was reduced to the taskbar.  It doesn't happen on other softwares/windows so far.  Not sure if that's important, but I want to point out that my taskbar is on the left monitor, the middle monitor being my main monitor.

**Comment by vegardlarsen** [comment]
@terrybr Does this happen with beta.9 as well?

There is a know issue in beta.10 that causes MaxTo to partially be unaware of DPI issues; this could affect what you are writing about here.

To try out beta.9 you would have to uninstall the version you have installed, and download and install the old beta [from here](https://maxto.net/release/beta).

**Comment by terrybr** [comment]
@vegardlarsen I uninstalled beta.10 and installed beta.9.  Same exact issue with Firefox.  Let me know if you want me to record a video or if you need anything from me to help you find the bug.

**Comment by vegardlarsen** [comment]
A video would be nice to illustrate the problem. :)

**Comment by terrybr** [comment]
I installed the v2.0.0rc1 and recorded a video which I attached to this comment.  I have three widescreen monitors, but for the sake of the video's resolution, I'm only capturing two of them.

I first try with Firefox showing that, when I first launch it, it has a previous window size (not maximized).  If I reduce it in its current size, and maximize it, there's no issue.  If I maximize the Firefox window, minimize it,  and then maximize it again, that's when the issue happens.  I then resize the window, and try to grab it, and you can see during the dragging it resizes the window again.

I'm also showing that it's not happening with another software (Chrome).

[Max.to.2.0.0rc1_issue.zip](https://github.com/digitalcreations/MaxTo/files/2894525/Max.to.2.0.0rc1_issue.zip)

**Comment by vegardlarsen** [comment]
That video was very illustrative. To reproduce:

1. Maximize Firefox (to the entire screen)
2. Minimize Firefox
3. Restore Firefox (observe wrong size)

**Comment by vegardlarsen** [comment]
This issue has been fixed for 2.0.0-rc.2. It has the same root cause as #346.

**Comment by terrybr** [comment]
I just installed the latest version 2.0.0-rc.2, but the issue is still present.

**Comment by vegardlarsen** [comment]
@terrybr Did you reboot afterwards and ensure that rc.2 is the version running?

**Comment by terrybr** [comment]
@vegardlarsen I did reboot, and 2.0.0-rc.2 is the version running.

[maxto-2.0.0-rc2-ff_bug.zip](https://github.com/digitalcreations/MaxTo/files/2955484/maxto-2.0.0-rc2-ff_bug.zip)

**Comment by vegardlarsen** [comment]
@terrybr Can you contact me on the support address so I can set you up with a private build tomorrow to see if we've fixed it on your machine now?

**Comment by terrybr** [comment]
@vegardlarsen Done.  Thanks!

**Comment by vegardlarsen** [comment]
@terrybr I haven't received your e-mail, so I don't know where to send it. :)

**Comment by terrybr** [comment]
@vegardlarsen That's the email address I sent the email to yesterday.  I will send one again.

**Comment by vegardlarsen** [comment]
We have confirmed with @terrybr that our second attempt at a fix works. Closing this issue again. :)

**Comment by pmalecka** [comment]
This still occurs when trying to drag a maximized Firefox window. Tested on 67b2 on Windows 10 x64.

**Comment by vegardlarsen** [comment]
@pmalecka Which version of MaxTo do you have?

**Comment by pmalecka** [comment]
@vegardlarsen 2.0.0-rc3

**Comment by pmalecka** [comment]
@vegardlarsen Just tried in 2.0.0, seems to be all good now.
Thanks for fixing it so quickly.
