### ISSUE TITLE
Inaccurate region size computation

### ISSUE THREAD

**Issue by zhoumin03** [digitalcreations/MaxTo#447]
**Describe the bug**
I have a 3840x1200 monitor with working area of size 3840x1160. I will be happy if the working area can be divided into 3 regions with the same size.

I am able to initialize the region setting (as in the 1st pic), and click "use region".
However, everytime I reopen the "chang region" window, the region size changes a little bit.

Look at the left-most region, its size changed from: 1280x1158 -> 1281x1158 -> 1282x1158.

It does not help if I store the region settings.

It seems that the setting of region size is stored in fraction and the size in pixel is computed from that fraction. Unfortunately, such computation may result in inaccuracy. Since we don't always change monitors settings, I hope the region size can be stored as integers (the number of pixels) instead of fraction (the proportion). 

Notice that 3840 is properly divided by 3, and each region has width of 1/3 (0.33333333....). The result of 3840x0.333333... can be easily rounded to the correct size of 1280. If storing fraction is a technical limitation that can not be avoided, maybe its better that we use rounding (instead of flooring or ceiling) when computing the number of pixels.

Thanks!

Friendly name: Generic PnP Monitor
Device name: \\.\DISPLAY1
Location identifier: \{18CC3AAB-4594-11E9-97AB-408D5C844EED}\0000
Serial number: HTJM200042
DPI (dots per inch): 96×96
Resolution: 3840×1200 @ 0, 0
Working area: 3840×1160 @ 0, 0

**To Reproduce**
1. Go to "chang region"
2. Divide the work area to 3 equal area (horizontially layout)
3. Click "change region" again
4. Repeat step 3

**Expected behavior**
Region size can be restored as it was saved.

**Screenshots**
![region1](https://user-images.githubusercontent.com/5674736/61781421-e67e1380-ae36-11e9-93f8-882f164858ed.png)
![region2](https://user-images.githubusercontent.com/5674736/61781423-e67e1380-ae36-11e9-8302-dd361217c403.png)
![region3](https://user-images.githubusercontent.com/5674736/61781424-e716aa00-ae36-11e9-9239-14c536a1054c.png)

**System information:**
 - Windows version: Win 10
 - MaxTo version: 2.0.1

**Additional context**
No

**Comment by zhoumin03** [comment]
I found this issue duplicated with #382 

This bug kills people with OCD... I think its definitely technically possible to fix it.

**Comment by vegardlarsen** [comment]
Thank you for your contribution. Had this been as simple as a floating point error, which is the issue you are describing, this would have been solved earlier. It is however not that simple.

Try this out (in C#, which MaxTo is written in):

```cs
var x = 3840 / 3f; // produces 1280 exactly
var y = x * 3f; // produces 3840 exactly

// not convinced?
var x = 3840 * 0.333333333333; // produces 1280 exactly
var y = x / 0.333333333333; // produces 3840 exactly
```

As you can see, this is not a rounding error. The problem is more complex, in the intricate workings of WPF's `GridSplitter`, Windows high-DPI support, and the fact that MaxTo deeply nests its `GridSplitter` controls in ways that require compensating for the drag handles.

I am closing this issue as a duplicate of #382.

**Comment by zhoumin03** [comment]
Thanks for your reply. Well, I understand now it is not as simple as rounding.
I still don't quite understand the essential cause of the inaccruate computation.

As on my computer, I have a monitor of resolution 3840x1200 with no DPI scaling.
I set the regions to 3 regions of equal size (1280x1158), and in the config.json, I got the following entry:

```
    {
      "type": "split",
      "splits": {
        "orientation": "Horizontal",
        "distance": 0.33320888957078548,
        "child1": null,
        "child2": {
          "orientation": "Horizontal",
          "distance": 0.50003736084229211,
          "child1": null,
          "child2": null
        }
      },
      "name": "Triple"
    }
```

Apparently, the fraction number is incorrect!
Since I set NO DPI scaling, the fraction should be 1280/3840=0.333333333..., but the fraction stored in `config.json` is 0.33320888957078548. If the region size is computed from that fraction, the pixels becomes 1279.522135951816‬.

In the region editor, we are awared that each region is of size 1280x1158, so the pixels number is accurately known. And accordingly, the `distance` stored in config could have been correctly identified as 0.3333333... and 0.500000 respectively. If not caused by rounding, I have no idea where the inaccuracy comes from.

I am a trial user of MaxTo, that meets many of my requirements perfectly and I am seriously considering paying for it. But this bug seems annoying. 

I understand that there are many procedures in the pixel -> fraction and fraction -> pixel conversions, but I have no idea why they are not inversible, even if regions are stored as fraction.

I do hope this bug can be fixed and I am willing to help fixing this issue.

Thank you.
