### ISSUE TITLE
Windows Stay Transparent after moving it.

### ISSUE THREAD

**Issue by RunSmarterIT** [digitalcreations/MaxTo#561]
When I move windows around, 50% of the time, they stay transparent.  

**To Reproduce**
Just move any windows in the Desktop

**Expected behavior**
Windows would return to no transparency after it would be dropped.

**Screenshots**
Imagine a windows but transparent enough that you can see the desktop underneath.

**System information:**
 - Windows version: 10 version 1909
 - MaxTo version [e.g. 22]

**Additional context**
Please collect and attach log files that may be relevant, but cut them down for brevity. For MaxTo crashes, please see `%AppData%\MaxTo\maxto.log`. For installer issues, please see `%LocalAppData%\SquirrelTemp\SquirrelSetup.log`
[maxto20200516.log](https://github.com/digitalcreations/MaxTo/files/4646763/maxto20200516.log)

**Comment by vegardlarsen** [comment]
@RunSmarterIT Which version of MaxTo are you running?

**Comment by blightfire** [comment]
Am randomly getting this issue as well on 2.1.0-Beta1

**Comment by vegardlarsen** [comment]
I have implemented a change in how this works, which hopefully should resolve the issue with some apps. That fix will be in 2.1.0-beta.2.

**Comment by thewavelength** [comment]
Still persists. Example application: foobar2000. Only relevant log entry:

```
2020-05-21 11:14:10 [CompanionX86@2.1.0.660] [Information] [MaxTo.Companion.MessageHandlers.DragWindowMessageHandler] Did not receive any moving events while dragging "Lostprophets - The Handsome Life Of Swing :: foobar2000" (0x"c062c"), used mouse position to find region "{X=0,Y=0,Width=962,Height=1550}".
```

**Comment by vegardlarsen** [comment]
Please open a new issue referencing this one. :)
