### ISSUE TITLE
Recipes with Load Preset not working

### ISSUE THREAD

**Issue by jtnydv** [digitalcreations/MaxTo#592]
**Describe the bug**
Any key combination with Load preset is not working.

**To Reproduce**
Set up a recipe with 
Trigger: Hotkey [Ctrl + Alt + Shift + F1]
Ingredients:
1. Highlight Regions
2. Load Preset

**Expected behavior**
Preset should change

**Screenshots**
![image](https://user-images.githubusercontent.com/14368729/86329135-5f9b0300-bc63-11ea-87d7-5c2a2df926c0.png)

**System information:**
- Windows version: 1909 (OS Build 18363.778)
- MaxTo version: 2.1.0-beta2, and 2.0.1 (Stable)

**Additional context**

**Comment by vegardlarsen** [comment]
@jtnydv Could you send me your `config.json` file with this recipe in it (or export the recipe from the settings dialog) to attach it here?

**Comment by jtnydv** [comment]
Where can I locate the config.json file?

**Comment by vegardlarsen** [comment]
`%AppData%\MaxTo\config.json` (that is a valid path, even though it looks weird)

**Comment by jtnydv** [comment]
[config.zip](https://github.com/digitalcreations/MaxTo/files/4862949/config.zip)

**Comment by vegardlarsen** [comment]
@jtnydv Which version of MaxTo did you take the screenshot from? This issue should have been fixed in 2.1.0-beta.2; and when I try to import your recipe and run it, it works well (aside from the fact that you highlight your regions before loading the new preset, so it shows the old regions)?

**Comment by jtnydv** [comment]
I'll remove everything and do a clean install and see if problem exists. Let me check and get back to you.

**Comment by jtnydv** [comment]
Still the same problem. Removed all the files in the Local and Roaming and reinstalled the beta version. Same issue.

**Comment by vegardlarsen** [comment]
Can you check your log files for more details? `%AppData%\MaxTo\maxto-20200702.log` (or something close to that)

**Comment by jtnydv** [comment]
```
2020-07-02 14:40:57 [Core@2.1.0.660] [Warning] [MaxTo.Core.Keyboard.RecipeExecutor] Received exception from command request 1 while executing '"Grid 1"'. Aborting.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at MaxTo.Core.Settings.CoreMonitorConfigurationManager.<UpdateConfiguration>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Regions.RegionService.<SetActiveRegionForMonitor>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Regions.RegionService.<SetActiveRegionForMonitor>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MaxTo.Core.Commands.Regions.ApplyCommand.<Execute>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandBase`2.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__2.MoveNext()
2020-07-02 14:40:57 [Core@2.1.0.660] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] 1 recipes was executed (0 succesfully)
```

**Comment by vegardlarsen** [comment]
@jtnydv Is this for the same recipe as before? The name is different. It does appear to be something related to the naming of monitors.

**Comment by jtnydv** [comment]
I tried making few adjustments here and there, maybe that's why names are different however if it's due to monitor names. How can I fix it?

**Comment by vegardlarsen** [comment]
@jtnydv You can try using "Primary monitor" (which is saved as `$primary` in the config file), or "Current monitor" (`$current`). Could you send me the updated `config.json` file before you make those changes as I can try again to reproduce it?
